sonar.projectKey=RayanHDev34_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
sonar.organization=rayanhdev34

sonar.sources=front/src,back/src
sonar.tests=front/src,back/src

sonar.exclusions=**/node_modules/**,**/*.spec.ts

# Front coverage (Angular)
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info

# Back coverage (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml