sonar.projectKey=RayanHDev34_Gerez-un-projet-collaboratif-en-integrant-une-demarche-CI-CD
sonar.organization=rayanhdev34

sonar.sources=front/src,back/src
sonar.tests=front/src,back/src

sonar.test.inclusions=**/*.spec.ts,**/*Test.java
sonar.exclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

sonar.java.binaries=back/target/classes